### PR TITLE
Updated yosay

### PR DESCRIPTION
**Pull request by jedireza**
@redonkulus doesn't look like much changed from 0.3.0 to 1.0.x:

https://github.com/yeoman/yosay/compare/v0.3.0...master

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
Does the generator still work locally with this change?

**Comment by jedireza** [comment]
It sure did.

**Comment by redonkulus** [comment]
:shipit:

**Pull request merged**
