### PR TITLE
Fix demo app's navigation history functionality.

### PR DESCRIPTION
**Pull request by JoshuaGross**
The main purpose of this PR is to fix navigation (in the default demo app currently, if you navigate from Home to About or vice-versa, the URL does not reflect the change).

It seemed easiest to switch to fluxible-router to accomplish this.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
This looks good, however, we just merged [another PR](https://github.com/yahoo/generator-fluxible/pull/19), please merge from master.

**Comment by redonkulus** [comment]
To get the release out for the gulp option, I've updated this locally and made [one minor fix](https://github.com/yahoo/generator-fluxible/commit/716a294c5708863607ac5ba36e3fb8e8a978ad3a) to add fluxible-router to the gulp package.json.

This is now merged into master, thanks!

**Comment by JoshuaGross** [comment]
Nice! Thanks for doing that for me, @redonkulus

**Pull request closed without merging**
